# =============================================================
# Check for New MegaLinter Version Workflow
#
# This workflow checks daily for new versions of the MegaLinter
# custom-builder action and creates a release if a new version is found.
#
# Usage:
# - Runs daily at 00:00 UTC via schedule
# - Can be manually triggered via workflow_dispatch
# - Compares MegaLinter tags with current repository tags
# - Creates a new release if a new MegaLinter version is detected
#
# The workflow will:
# 1. Fetch all tags from oxsecurity/megalinter repository
# 2. Fetch all tags from the current repository
# 3. Find new tags that exist in MegaLinter but not in current repo
# 4. Create a release with the new version tag
# 5. The release will trigger megalinter-custom-flavor-builder.yml
#
# Required permissions:
#   - contents: write (to create releases and tags)
#
# Optional repository secrets (for triggering workflows):
#   - PAT_TOKEN: Personal Access Token with 'repo' and 'workflow' scopes
#     If not provided, the workflow will still create releases, but won't
#     be able to manually trigger the builder workflow (it will rely on
#     the automatic release trigger instead).
#
# To create a PAT:
#   1. Go to GitHub Settings > Developer settings > Personal access tokens > Tokens (classic)
#   2. Click "Generate new token (classic)"
#   3. Give it a descriptive name (e.g., "MegaLinter Auto-Release")
#   4. Select scopes: 'repo' (full control) and 'workflow' (update workflows)
#   5. Click "Generate token" and copy the token
#   6. In your repository, go to Settings > Secrets and variables > Actions
#   7. Click "New repository secret"
#   8. Name: PAT_TOKEN, Value: paste your token
# =============================================================

name: Check for New MegaLinter Version

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-new-version:
    name: Check for New MegaLinter Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch MegaLinter Repository Tags
        id: fetch-megalinter-tags
        run: |
          echo "Fetching tags from oxsecurity/megalinter..."
          
          # Fetch all tags from MegaLinter repository (filtering for version tags only)
          MEGALINTER_TAGS=$(git ls-remote --tags --refs https://github.com/oxsecurity/megalinter.git | \
            grep -E 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$' | \
            sed 's/.*refs\/tags\///' | \
            sort -V | \
            tail -n 20)
          
          echo "Latest MegaLinter tags:"
          echo "$MEGALINTER_TAGS"
          
          # Get the latest tag
          LATEST_MEGALINTER_TAG=$(echo "$MEGALINTER_TAGS" | tail -n 1)
          echo "latest_tag=$LATEST_MEGALINTER_TAG" >> $GITHUB_OUTPUT
          
          # Save all tags to a file
          echo "$MEGALINTER_TAGS" > megalinter_tags.txt

      - name: Fetch Current Repository Tags
        id: fetch-repo-tags
        run: |
          echo "Fetching tags from current repository..."
          
          # Fetch all version tags from current repository
          REPO_TAGS=$(git tag -l 'v*' | sort -V)
          
          echo "Current repository tags:"
          echo "$REPO_TAGS"
          
          # Get the latest tag from current repository
          if [ -z "$REPO_TAGS" ]; then
            LATEST_REPO_TAG=""
            echo "No existing tags in repository"
          else
            LATEST_REPO_TAG=$(echo "$REPO_TAGS" | tail -n 1)
            echo "Latest repository tag: $LATEST_REPO_TAG"
          fi
          
          echo "latest_repo_tag=$LATEST_REPO_TAG" >> $GITHUB_OUTPUT

      - name: Find New Version
        id: find-new-version
        run: |
          echo "Comparing versions..."
          
          LATEST_MEGALINTER_TAG="${{ steps.fetch-megalinter-tags.outputs.latest_tag }}"
          LATEST_REPO_TAG="${{ steps.fetch-repo-tags.outputs.latest_repo_tag }}"
          
          echo "Latest MegaLinter tag: $LATEST_MEGALINTER_TAG"
          echo "Latest repository tag: $LATEST_REPO_TAG"
          
          # Function to compare semantic versions
          version_greater_than() {
            # Remove 'v' prefix for comparison
            ver1="${1#v}"
            ver2="${2#v}"
            
            # Use sort -V to compare versions
            if [ "$(printf '%s\n' "$ver1" "$ver2" | sort -V | tail -n1)" = "$ver1" ] && [ "$ver1" != "$ver2" ]; then
              return 0  # ver1 > ver2
            else
              return 1  # ver1 <= ver2
            fi
          }
          
          # Check if we should create a new release
          if [ -z "$LATEST_REPO_TAG" ]; then
            echo "No existing tags in repository. Will create release for $LATEST_MEGALINTER_TAG"
            echo "new_version_found=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_MEGALINTER_TAG" >> $GITHUB_OUTPUT
          elif version_greater_than "$LATEST_MEGALINTER_TAG" "$LATEST_REPO_TAG"; then
            echo "✅ New version found! $LATEST_MEGALINTER_TAG > $LATEST_REPO_TAG"
            echo "new_version_found=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_MEGALINTER_TAG" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ No new version. Repository is up to date."
            echo "new_version_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release for New Version
        if: steps.find-new-version.outputs.new_version_found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.find-new-version.outputs.new_version }}
        run: |
          echo "Creating release for version $NEW_VERSION..."
          
          # Create a release using GitHub CLI
          gh release create "$NEW_VERSION" \
            --title "MegaLinter Custom Flavor $NEW_VERSION" \
            --notes "Automated release to sync with MegaLinter version $NEW_VERSION.

          This release was automatically created to build a custom MegaLinter flavor based on the upstream MegaLinter release $NEW_VERSION.
          
          For more information about changes in this version, see the [MegaLinter changelog](https://github.com/oxsecurity/megalinter/releases/tag/$NEW_VERSION)." \
            --latest

      - name: Trigger Custom Flavor Builder Workflow
        if: steps.find-new-version.outputs.new_version_found == 'true'
        env:
          # Use PAT_TOKEN if available, otherwise fall back to GITHUB_TOKEN
          # Note: GITHUB_TOKEN doesn't have permission to trigger workflows
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          echo "Triggering megalinter-custom-flavor-builder workflow..."
          
          # Trigger the workflow using GitHub CLI
          if gh workflow run megalinter-custom-flavor-builder.yml --ref main 2>&1 | tee workflow_trigger.log; then
            echo "✅ Builder workflow triggered successfully"
          else
            if grep -q "Resource not accessible by integration" workflow_trigger.log || grep -q "HTTP 403" workflow_trigger.log; then
              echo "::error::❌ Unable to trigger workflow due to insufficient token permissions."
              echo "::error::The release was created, but the builder workflow could not be manually triggered."
              echo ""
              echo "::error::To fix this, create a Personal Access Token (PAT) with proper permissions:"
              echo "::error::1. Go to GitHub Settings > Developer settings > Personal access tokens > Tokens (classic)"
              echo "::error::2. Click 'Generate new token (classic)'"
              echo "::error::3. Name it 'MegaLinter Auto-Release'"
              echo "::error::4. Select scopes: 'repo' (full control) and 'workflow' (update workflows)"
              echo "::error::5. Generate and copy the token"
              echo "::error::6. In repository Settings > Secrets and variables > Actions"
              echo "::error::7. Create new secret: Name='PAT_TOKEN', Value=<your-token>"
              echo ""
              echo "::error::NOTE: The release event should still trigger the builder workflow automatically."
              exit 1
            else
              echo "::error::Failed to trigger workflow for unknown reason"
              cat workflow_trigger.log
              exit 1
            fi
          fi

      - name: Summary
        if: always()
        run: |
          echo "## Check for New MegaLinter Version Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          LATEST_MEGALINTER_TAG="${{ steps.fetch-megalinter-tags.outputs.latest_tag }}"
          LATEST_REPO_TAG="${{ steps.fetch-repo-tags.outputs.latest_repo_tag }}"
          
          if [ "${{ steps.find-new-version.outputs.new_version_found }}" == "true" ]; then
            echo "✅ New version found: **${{ steps.find-new-version.outputs.new_version }}**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "A new release has been created, which will trigger the custom flavor builder workflow." >> $GITHUB_STEP_SUMMARY
            
            # Check if PAT_TOKEN is configured
            if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### ⚠️ Optional: Configure PAT for Direct Workflow Triggering" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "The release will automatically trigger the builder workflow, but you can also enable manual triggering:" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "**To create and configure a Personal Access Token (PAT):**" >> $GITHUB_STEP_SUMMARY
              echo "1. Go to [GitHub Settings > Developer settings > Personal access tokens > Tokens (classic)](https://github.com/settings/tokens)" >> $GITHUB_STEP_SUMMARY
              echo "2. Click **Generate new token (classic)**" >> $GITHUB_STEP_SUMMARY
              echo "3. Name: \`MegaLinter Auto-Release\`" >> $GITHUB_STEP_SUMMARY
              echo "4. Select scopes: ✅ **repo** (full control) and ✅ **workflow** (update workflows)" >> $GITHUB_STEP_SUMMARY
              echo "5. Click **Generate token** and copy it" >> $GITHUB_STEP_SUMMARY
              echo "6. Go to [Repository Settings > Secrets and variables > Actions](https://github.com/${{ github.repository }}/settings/secrets/actions)" >> $GITHUB_STEP_SUMMARY
              echo "7. Click **New repository secret**" >> $GITHUB_STEP_SUMMARY
              echo "8. Name: \`PAT_TOKEN\`, Value: paste your token" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "ℹ️ No new versions found. Repository is up to date with MegaLinter." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version Comparison:**" >> $GITHUB_STEP_SUMMARY
          echo "- Latest MegaLinter version: **$LATEST_MEGALINTER_TAG**" >> $GITHUB_STEP_SUMMARY
          
          if [ -n "$LATEST_REPO_TAG" ]; then
            echo "- Latest repository version: **$LATEST_REPO_TAG**" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Latest repository version: **No tags found**" >> $GITHUB_STEP_SUMMARY
          fi
